name: ci

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - name: Check npm version
        run: npm -v

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run linter
        run: npm run test

      - name: Build source code
        run: npm run dist
