name: ci

permissions:
  contents: read
  id-token: write
  pages: write

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  # --------------PREPARE REPOSITORY--------------
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
            **/dist
            **/build
          key: ${{ runner.os }}-prepare-${{ env.cache-name }}-${{ github.sha }}

      - name: Set Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Set npm version
        run: npm i -g npm@8

      - name: Install dependencies
        run: npm ci

  # --------------BUILD DIST--------------
  dist:
    needs: [prepare]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use node modules cache
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
            **/dist
            **/build
          key: ${{ runner.os }}-prepare-${{ env.cache-name }}-${{ github.sha }}

      - name: Generate dist files
        run: |
          npm run dist -w @devoinc/genesys-tokens
          npm run dist -w @devoinc/genesys-tokens-cli
          cd tokens-cli && npm link && cd ..
          npm run dist -w @devoinc/genesys-tokens-types

  # --------------RUN LINTER--------------
  lint:
    needs: [prepare]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use node modules cache
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
            **/dist
            **/build
          key: ${{ runner.os }}-prepare-${{ env.cache-name }}-${{ github.sha }}

      - name: Run linter
        run: npm run lint

  # --------------RUN UNIT TESTS--------------
  unit-test:
    needs: [prepare]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use node modules cache
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
            **/dist
            **/build
          key: ${{ runner.os }}-prepare-${{ env.cache-name }}-${{ github.sha }}

      - name: Run Jest
        run: npm run test

  # --------------RUN MUTATION TESTS--------------
  mutation-test:
    needs: [unit-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use node modules cache
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
            **/dist
            **/build
          key: ${{ runner.os }}-prepare-${{ env.cache-name }}-${{ github.sha }}

      - name: Setup results folder
        run: mkdir mutation-test-results

      - name: Execute Stryker
        run: npm run stryker

      - name: Post Stryker
        run: |
          cd mutation-test-results
          cp /home/runner/work/genesys-tokens/genesys-tokens/tokens/reports/mutation/mutation.html stryker-report.html
          cd ..
      - name: Upload artifact with results
        uses: actions/upload-artifact@v3
        with:
          name: mutation-test-results
          path: mutation-test-results
