name: release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Select version to release
        options:
          - major
          - minor
          - patch
          - auto
        default: auto
        required: true

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"
          registry-url: https://registry.npmjs.org/

      - name: Set npm version
        run: npm i -g npm@7

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run linter
        run: npm run lint

      - name: Build source code
        run: npm run dist

      - name: Setup Git config
        run: |
          git config --global user.name 'Devo GitHub Action'
          git config --global user.email 'desa@devo.com'

      - name: Publish major (if applicable)
        if: ${{ github.event.inputs.version == 'major' }}
        run: npm run release:ci -- major

      - name: Publish minor (if applicable)
        if: ${{ github.event.inputs.version == 'minor' }}
        run: npm run release:ci -- minor

      - name: Publish patch (if applicable)
        if: ${{ github.event.inputs.version == 'patch' }}
        run: npm run release:ci -- patch

      - name: Publish auto (if applicable)
        if: ${{ github.event.inputs.version == 'auto' }}
        run: npm run release:ci
